#' @title BRENDA tissue ontology obo file. using version 2021/10
#' @description BTO:0000000 is set to be "unknown"
#' @format A data frame with columns `ID` and `Name`.
#' @docType data
#' @keywords datasets
#' @export
BRENDA <- readRDS(file.path(system.file("extdata", package = "OmicSignature"), "BRENDA_2021.rds"))

#' @title predefined platform list
#' @description a list of predefined platform names
#' @format A character vector.
#' @docType data
#' @keywords datasets
#' @export
# GEOplatform <- readRDS(file.path(system.file("extdata", package = "OmicSignature"), "GEOplatform_2024.rds"))
predefined_platforms <- readLines(file.path(system.file("extdata", package = "OmicSignature"), "predefined_platforms.txt"))

#' @title predefined organism list
#' @description a list of predefined organism names
#' @format A character vector.
#' @docType data
#' @keywords datasets
#' @export
predefined_organisms <- readLines(file.path(system.file("extdata", package = "OmicSignature"), "predefined_organisms.txt"))

#' @title predefined assay type list
#' @description a list of predefined assay type names
#' @format A character vector.
#' @docType data
#' @keywords datasets
#' @export
predefined_assaytypes <- readLines(file.path(system.file("extdata", package = "OmicSignature"), "predefined_assaytypes.txt"))

#' Example signatures for comparing OmicSignature lists
#'
#' A named list of four `OmicSignature` objects prepared for examples and
#' vignettes that demonstrate `compare_omic_signatures()` and
#' `signature_similarity_heatmap()`. The objects come from local signature RDS
#' files used in the comparison workflow and have their `difexp` tables reduced
#' to the union of features present in the stored signatures to keep the package
#' data footprint small.
#'
#' @format A named list with four `OmicSignature` objects:
#' \describe{
#'   \item{e7386_hsc3}{E7386 versus DMSO signature for HSC3 cells.}
#'   \item{e7386_cal27}{E7386 versus DMSO signature for CAL27 cells.}
#'   \item{icg001_hsc3}{ICG001 signature for HSC3 cells.}
#'   \item{icg001_cal27}{ICG001 signature for CAL27 cells.}
#' }
#' @source Generated by `data-raw/create_compare_signatures_data.R` from
#' local signature RDS files under `SIGREPO_PATH` or
#' `~/research/projects/sigRepo`.
#' @usage data(compare_signatures_example)
#' @docType data
#' @keywords datasets
"compare_signatures_example"

#' Simulated signatures for label-pairing examples
#'
#' A named list of three simulated `OmicSignature` objects designed to
#' demonstrate explicit `label_pairing` control in `compare_omic_signatures()`.
#' Each object contains two label-specific signatures of 10 features each and a
#' 100-row `difexp` table.
#'
#' The simulated overlap structure makes `signature_a`'s `treated` label most
#' similar to `signature_b`'s `up` label, then to `signature_c`'s `resistant`
#' label. Likewise, `signature_a`'s `control` label is most similar to
#' `signature_b`'s `down` label, then to `signature_c`'s `sensitive` label.
#'
#' @format A named list with three `OmicSignature` objects:
#' \describe{
#'   \item{signature_a}{Simulated signature with `treated` and `control` labels.}
#'   \item{signature_b}{Simulated signature with `up` and `down` labels.}
#'   \item{signature_c}{Simulated signature with `resistant` and `sensitive` labels.}
#' }
#' @source Generated by `data-raw/create_compare_label_pairing_data.R`.
#' @usage data(compare_label_pairing_example)
#' @docType data
#' @keywords datasets
"compare_label_pairing_example"

#' Simulated signatures mixing bi-directional and uni-directional signatures
#'
#' A named list of four simulated `OmicSignature` objects designed to
#' demonstrate `compare_omic_signatures()`'s handling of a mix of
#' bi-directional and uni-directional signatures. `signature_a`, `signature_b`,
#' and `signature_c` are identical to their counterparts in
#' `compare_label_pairing_example`. `signature_d` is uni-directional (no
#' `group_label` contrast) and shares the same 100-gene universe.
#'
#' `signature_d`'s features overlap strongly with `signature_a`'s `treated`
#' label, `signature_b`'s `up` label, and `signature_c`'s `resistant` label,
#' and not at all with any signature's `control`/`down`/`sensitive` label.
#'
#' @format A named list with four `OmicSignature` objects:
#' \describe{
#'   \item{signature_a}{Simulated bi-directional signature with `treated` and `control` labels.}
#'   \item{signature_b}{Simulated bi-directional signature with `up` and `down` labels.}
#'   \item{signature_c}{Simulated bi-directional signature with `resistant` and `sensitive` labels.}
#'   \item{signature_d}{Simulated uni-directional signature (no group_label contrast).}
#' }
#' @source Generated by `data-raw/create_compare_mixed_direction_data.R`.
#' @usage data(compare_mixed_direction_example)
#' @docType data
#' @keywords datasets
"compare_mixed_direction_example"

#' Simulated signatures with only uni-directional signatures
#'
#' A named list of three simulated uni-directional `OmicSignature` objects
#' (no `group_label` contrast), designed to demonstrate
#' `compare_omic_signatures()`'s flat, single-comparison output for
#' `method = "overlap"` when none of the compared signatures has group_label
#' levels to pair on.
#'
#' `uni_x` and `uni_y` share 5 of their 10 features each; `uni_z` shares
#' nothing with either.
#'
#' @format A named list with three `OmicSignature` objects:
#' \describe{
#'   \item{uni_x}{Simulated uni-directional signature, genes 001-010.}
#'   \item{uni_y}{Simulated uni-directional signature, genes 006-015.}
#'   \item{uni_z}{Simulated uni-directional signature, genes 050-059.}
#' }
#' @source Generated by `data-raw/create_compare_unidirectional_data.R`.
#' @usage data(compare_unidirectional_example)
#' @docType data
#' @keywords datasets
"compare_unidirectional_example"
