#' @title BRENDA tissue ontology obo file. using version 2021/10
#' @description BTO:0000000 is set to be "unknown"
#' @export
BRENDA <- readRDS(file.path(system.file("extdata", package = "OmicSignature"), "BRENDA_2021.rds"))

#' @title predefined platform list
#' @description a list of predefined platform names 
#' @export
# GEOplatform <- readRDS(file.path(system.file("extdata", package = "OmicSignature"), "GEOplatform_2024.rds"))
predefined_platforms <- readLines(file.path(system.file("extdata", package = "OmicSignature"), "predefined_platforms.txt"))

#' @title predefined organism list
#' @description a list of predefined organism names 
#' @export
predefined_organisms <- readLines(file.path(system.file("extdata", package = "OmicSignature"), "predefined_organisms.txt"))

#' @title predefined assay type list
#' @description a list of predefined assay type names 
#' @export
predefined_assaytypes <- readLines(file.path(system.file("extdata", package = "OmicSignature"), "predefined_assaytypes.txt"))

#' Example signatures for comparing OmicSignature lists
#'
#' A named list of four `OmicSignature` objects prepared for examples and
#' vignettes that demonstrate `compare_omic_signatures()` and
#' `signature_similarity_heatmap()`. The objects come from local signature RDS
#' files used in the comparison workflow and have their `difexp` tables reduced
#' to the union of features present in the stored signatures to keep the package
#' data footprint small.
#'
#' @format A named list with four `OmicSignature` objects:
#' \describe{
#'   \item{e7386_hsc3}{E7386 versus DMSO signature for HSC3 cells.}
#'   \item{e7386_cal27}{E7386 versus DMSO signature for CAL27 cells.}
#'   \item{icg001_hsc3}{ICG001 signature for HSC3 cells.}
#'   \item{icg001_cal27}{ICG001 signature for CAL27 cells.}
#' }
#' @source Generated by `data-raw/create_compare_signatures_data.R` from
#' local signature RDS files under `SIGREPO_PATH` or
#' `~/research/projects/sigRepo`.
#' @usage data(compare_signatures_example)
#' @docType data
#' @keywords datasets
"compare_signatures_example"

#' Simulated signatures for label-pairing examples
#'
#' A named list of three simulated `OmicSignature` objects designed to
#' demonstrate explicit `label_pairing` control in `compare_omic_signatures()`.
#' Each object contains two label-specific signatures of 10 features each and a
#' 100-row `difexp` table.
#'
#' The simulated overlap structure makes `signature_a`'s `treated` label most
#' similar to `signature_b`'s `up` label, then to `signature_c`'s `resistant`
#' label. Likewise, `signature_a`'s `control` label is most similar to
#' `signature_b`'s `down` label, then to `signature_c`'s `sensitive` label.
#'
#' @format A named list with three `OmicSignature` objects:
#' \describe{
#'   \item{signature_a}{Simulated signature with `treated` and `control` labels.}
#'   \item{signature_b}{Simulated signature with `up` and `down` labels.}
#'   \item{signature_c}{Simulated signature with `resistant` and `sensitive` labels.}
#' }
#' @source Generated by `data-raw/create_compare_label_pairing_data.R`.
#' @usage data(compare_label_pairing_example)
#' @docType data
#' @keywords datasets
"compare_label_pairing_example"
